// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoBlogUygulama.Data;

#nullable disable

namespace PhotoBlogUygulama.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20240124064722_Ilk")]
    partial class Ilk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhotoBlogUygulama.Data.Gonderi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimYolu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Gonderiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Denizin kokusu...",
                            ResimYolu = "deniz.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Manzarayi izliyorum gözlerim kapali...",
                            ResimYolu = "manzara.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
